### ISSUE TITLE
no data for resource 'sysadmins' title 'sysadmins'

### ISSUE THREAD

**Issue by juasiepo** [mthibaut/puppet-users#1]
Hi,

I am trying to use your module but I get the following error:
Notice: no data for resource 'sysadmins' title 'sysadmins'
Notice: /Stage[main]/Base/Users[sysadmins]/Notify[no data for resource 'sysadmins' title 'sysadmins']/message: defined 'message' as 'no data for resource 'sy
sadmins' title 'sysadmins''

Here you are my yaml file:

users_sysadmins:
    juanillo:
        ensure: present
        uid: 1100
        gid: juan
        groups: sudo
        comment: Juan
        managehome: true

I think hiera is set properly as running it manually shows the values properly:
defaults.yaml
# hiera users_sysadmins

{"juanillo"=>{"gid"=>"juan", "uid"=>1100, "groups"=>"sudo", "comment"=>"Juan", "managehome"=>true, "ensure"=>"present"}}

Any Idea what am I doing wrong?

Thank for your time

Best regards

**Comment by mthibaut** [comment]
Hi,

Sorry, I can't reproduce this problem. You can try this:

node /mynode/ {
        $mytest = hiera("users_sysadmins", "not found")
        notify { "$mytest": }
}

Does the notify print out the hiera data?

## 

maarten

**Comment by juasiepo** [comment]
Hi,
It returns the following:
Notice: /Stage[main]//Node[puppet]/Notify[not found]/message: current_value absent, should be not found (noop)

So it seems that it is hiera not working well with puppet on my system.

Thank you for your time

Regards

**Comment by juasiepo** [comment]
Hi,

It was a problem with my configuration as hiera package keeps the hiera.yaml in /etc and puppet expected it in /etc/puppet/hiera.yaml

That's the reason it worked in the command line and not within a manifest.

Thank you for your time

**Comment by juasiepo** [comment]
Hi,

It was a problem with my configuration as hiera package keeps the hiera.yaml in /etc and puppet expected it in /etc/puppet/hiera.yaml

That's the reason it worked in the command line and not within a manifest.

Thank you for your time
